### ISSUE TITLE
Apex Test Class Error on Deployment

### ISSUE THREAD

**Issue by colePrato-zz** [ericrsmith35/Flow-PB-List-View-with-Batch-Delete#1]
![image](https://user-images.githubusercontent.com/43420867/92963402-62268f80-f440-11ea-9f81-f352db04ee00.png)

Class: GetFlowInfoAdvancedTest

Error: System.LimitException: Too many SOQL queries: 101
Stack Trace: Class.GetFlowInfoAdvanced.getFlowDetails: line 170, column 1 Class.GetFlowInfoAdvancedTest.test: line 17, column 1

**Comment by ericrsmith35** [comment]
It looks like you might have a large number of flows in the org you are installing this into.  You can try adding a letter value in line 11 of GetFlowInfoAdvancedTest.cls that matches the first letter of the name of the first flow (alphabetically) in your org and then retry the install.  

Let me know if you are not able to make this change and we can try something else.

**Comment by ericrsmith35** [comment]
@colePrato Actually try it again as is.  I've updated the Test to try and load fewer records.

**Comment by colePrato-zz** [comment]
@ericrsmith35 still getting the same error.

**Comment by ericrsmith35** [comment]
I made another change.  I hope you don't mind trying again.

**Comment by colePrato-zz** [comment]
@ericrsmith35 that resolved the issue with the error, now I have a code coverage error on FlowDatatableDescriptor @ 5% coverage. I will take a look and see if this is an issue on my end as well.

**Comment by cadillacben** [comment]
@colePrato-zz How did you resolve the 5% coverage on FlowDatatableDescriptor?  I'm getting the same thing while trying to deploy.
@ericrsmith35 is there a test class meant to cover this one that I'm missing?
