### ISSUE TITLE
c:datatable component doesn't implement any marker interface that's supported for flows of type Flow

### ISSUE THREAD

**Issue by RomanTheCube** [ericrsmith35/Flow-PB-List-View-with-Batch-Delete#2]
Getting errors attempting to deploy to production:
DisplayListView (Screen Component) - The c:datatable component doesn't implement any marker interface that's supported for flows of type Flow.
DisplayDatatable (Screen Component) - The c:datatable component doesn't implement any marker interface that's supported for flows of type Flow.

Are there any instructions on how to **uninstall** this from an org? I would like to remove it completely from sandbox.

![image](https://user-images.githubusercontent.com/25043249/103556163-381d3100-4e66-11eb-8ec4-e129c25676fd.png)

**Comment by ericrsmith35** [comment]
I tried following the 6 installation steps for a new org and was unable to recreate this issue.  To uninstall, the best thing to do is to delete the 7 Flows that start with “Flow and Process Builder“.
